<?xml version="1.0" encoding="utf-8"?><Database Name="CSDLNhaHang" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CSDLNhaHang;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="CSDLNhaHangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="maHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Hang_ChiTietHoaDon" Member="HangLinq" Storage="_Hang" ThisKey="maHang" OtherKey="maHang" Type="HangLinq" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNhanVien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="chungMinhThu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tenTaiKhoan" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="HoaDon" />
      <Association Name="TaiKhoan_NhanVien" Member="TaiKhoan" ThisKey="tenTaiKhoan" OtherKey="tenTaiKhoan" Type="TaiKhoan" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Hang" Member="HangLinqs">
    <Type Name="HangLinq">
      <Column Name="maHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="donViTinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="donGia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="soLuongCon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maLoaiHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maNhaCungCap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Hang_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="maHang" OtherKey="maHang" Type="ChiTietHoaDon" />
      <Association Name="LoaiHang_Hang" Member="LoaiHang" ThisKey="maLoaiHang" OtherKey="maLoaiHang" Type="LoaiHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhaCungCapLinq_Hang" Member="NhaCungCapLinq" ThisKey="maNhaCungCap" OtherKey="maNhaCungCap" Type="NhaCungCapLinq" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="maHoaDon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngayGioTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="maKhachHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="ChiTietHoaDon" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="maLoaiKhachHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="HoaDon" />
      <Association Name="LoaiKhachHang_KhachHang" Member="LoaiKhachHang" ThisKey="maLoaiKhachHang" OtherKey="maLoaiKhachHang" Type="LoaiKhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHang" Member="LoaiHangs">
    <Type Name="LoaiHang">
      <Column Name="maLoaiHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoaiHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiHang_Hang" Member="HangLinqs" Storage="_Hangs" ThisKey="maLoaiHang" OtherKey="maLoaiHang" Type="HangLinq" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiKhachHang" Member="LoaiKhachHangs">
    <Type Name="LoaiKhachHang">
      <Column Name="maLoaiKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoaiKhachHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiKhachHang_KhachHang" Member="KhachHangs" ThisKey="maLoaiKhachHang" OtherKey="maLoaiKhachHang" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCapLinqs">
    <Type Name="NhaCungCapLinq">
      <Column Name="maNhaCungCap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNhaCungCap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="NhaCungCapLinq_Hang" Member="HangLinqs" Storage="_Hangs" ThisKey="maNhaCungCap" OtherKey="maNhaCungCap" Type="HangLinq" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="tenTaiKhoan" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="quyen" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="TaiKhoan_NhanVien" Member="NhanViens" ThisKey="tenTaiKhoan" OtherKey="tenTaiKhoan" Type="NhanVien" />
    </Type>
  </Table>
</Database>